/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s089_1
#  OS:                Linux x86_64(Host ID ieng6-240)
#  Generated on:      Fri Feb 26 11:58:38 2016
#  Design:            usb_phy
#  Command:           saveNetlist usb_phy_final.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s089_1
#  OS:                Linux x86_64(Host ID ieng6-240)
#  Generated on:      Fri Feb 26 11:17:22 2016
#  Design:            usb_phy
#  Command:           saveNetlist usb_phy.v
###############################################################
*/
module usb_phy (
	clk, 
	rst, 
	phy_tx_mode, 
	usb_rst, 
	txdp, 
	txdn, 
	txoe, 
	rxd, 
	rxdp, 
	rxdn, 
	DataOut_i, 
	TxValid_i, 
	TxReady_o, 
	RxValid_o, 
	RxActive_o, 
	RxError_o, 
	DataIn_o, 
	LineState_o);
   input clk;
   input rst;
   input phy_tx_mode;
   output usb_rst;
   output txdp;
   output txdn;
   output txoe;
   input rxd;
   input rxdp;
   input rxdn;
   input [7:0] DataOut_i;
   input TxValid_i;
   output TxReady_o;
   output RxValid_o;
   output RxActive_o;
   output RxError_o;
   output [7:0] DataIn_o;
   output [1:0] LineState_o;

   // Internal wires
   wire clk__L2_N3;
   wire clk__L2_N2;
   wire clk__L2_N1;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire n709;
   wire fs_ce;
   wire N23;
   wire i_tx_phy_state_0_;
   wire i_tx_phy_state_1_;
   wire i_tx_phy_state_2_;
   wire i_tx_phy_txoe_r2;
   wire i_tx_phy_append_eop_sync4;
   wire i_tx_phy_append_eop_sync3;
   wire i_tx_phy_append_eop_sync1;
   wire i_tx_phy_append_eop_sync2;
   wire i_tx_phy_txoe_r1;
   wire i_tx_phy_sd_nrzi_o;
   wire i_tx_phy_one_cnt_0_;
   wire i_tx_phy_one_cnt_1_;
   wire i_tx_phy_one_cnt_2_;
   wire i_tx_phy_sft_done_r;
   wire i_tx_phy_sft_done;
   wire i_tx_phy_bit_cnt_0_;
   wire i_tx_phy_bit_cnt_1_;
   wire i_tx_phy_bit_cnt_2_;
   wire i_tx_phy_data_done;
   wire i_tx_phy_tx_ip_sync;
   wire i_tx_phy_tx_ip;
   wire i_tx_phy_ld_data;
   wire i_tx_phy_N29;
   wire i_rx_phy_N149;
   wire i_rx_phy_rx_valid1;
   wire i_rx_phy_bit_cnt_0_;
   wire i_rx_phy_bit_cnt_1_;
   wire i_rx_phy_bit_cnt_2_;
   wire i_rx_phy_N127;
   wire i_rx_phy_one_cnt_0_;
   wire i_rx_phy_one_cnt_1_;
   wire i_rx_phy_one_cnt_2_;
   wire i_rx_phy_shift_en;
   wire i_rx_phy_sd_nrzi;
   wire i_rx_phy_sd_r;
   wire i_rx_phy_rx_valid_r;
   wire i_rx_phy_fs_state_0_;
   wire i_rx_phy_fs_state_1_;
   wire i_rx_phy_fs_state_2_;
   wire i_rx_phy_fs_ce_r2;
   wire i_rx_phy_fs_ce_r1;
   wire i_rx_phy_N34;
   wire i_rx_phy_dpll_state_0_;
   wire i_rx_phy_rxd_r;
   wire i_rx_phy_se0_s;
   wire i_rx_phy_rxdn_s;
   wire i_rx_phy_N32;
   wire i_rx_phy_rxdn_s_r;
   wire i_rx_phy_N31;
   wire i_rx_phy_rxdn_s0;
   wire i_rx_phy_rxdp_s;
   wire i_rx_phy_N30;
   wire i_rx_phy_rxdp_s_r;
   wire i_rx_phy_N29;
   wire i_rx_phy_rxdp_s0;
   wire i_rx_phy_rxd_s;
   wire i_rx_phy_rxd_s1;
   wire i_rx_phy_rxd_s0;
   wire i_rx_phy_N25;
   wire i_rx_phy_rx_en;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n252;
   wire n299;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n514;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n532;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire n549;
   wire n550;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n562;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n573;
   wire n574;
   wire n575;
   wire n576;
   wire n577;
   wire n578;
   wire n579;
   wire n580;
   wire n581;
   wire n582;
   wire n583;
   wire n584;
   wire n585;
   wire n586;
   wire n587;
   wire n588;
   wire n589;
   wire n590;
   wire n591;
   wire n592;
   wire n593;
   wire n594;
   wire n595;
   wire n596;
   wire n597;
   wire n598;
   wire n599;
   wire n600;
   wire n601;
   wire n602;
   wire n603;
   wire n604;
   wire n605;
   wire n606;
   wire n607;
   wire n608;
   wire n609;
   wire n610;
   wire n611;
   wire n612;
   wire n613;
   wire n614;
   wire n615;
   wire n616;
   wire n617;
   wire n618;
   wire n619;
   wire n620;
   wire n621;
   wire n622;
   wire n623;
   wire n624;
   wire n625;
   wire n626;
   wire n627;
   wire n628;
   wire n629;
   wire n630;
   wire n631;
   wire n632;
   wire n633;
   wire n634;
   wire n635;
   wire n636;
   wire n637;
   wire n638;
   wire n639;
   wire n640;
   wire n641;
   wire n642;
   wire n643;
   wire n644;
   wire n645;
   wire n646;
   wire n647;
   wire n648;
   wire n649;
   wire n650;
   wire n651;
   wire n652;
   wire n653;
   wire n654;
   wire n655;
   wire n656;
   wire n657;
   wire n658;
   wire n659;
   wire n660;
   wire n661;
   wire n662;
   wire n663;
   wire n664;
   wire n665;
   wire n666;
   wire n667;
   wire n668;
   wire n669;
   wire n670;
   wire n671;
   wire n672;
   wire n673;
   wire n674;
   wire n675;
   wire n676;
   wire n677;
   wire n678;
   wire n679;
   wire n680;
   wire n681;
   wire n682;
   wire n683;
   wire n684;
   wire n685;
   wire n686;
   wire n687;
   wire n688;
   wire n689;
   wire n690;
   wire n691;
   wire n692;
   wire n693;
   wire n694;
   wire n695;
   wire n696;
   wire n697;
   wire n698;
   wire n699;
   wire n700;
   wire n701;
   wire n702;
   wire n703;
   wire n704;
   wire n705;
   wire n706;
   wire n707;
   wire n708;
   wire [4:0] rst_cnt;
   wire [7:0] i_tx_phy_hold_reg;
   wire [5:0] i_tx_phy_hold_reg_d;

   bf01m40 clk__L2_I3 (.Z(clk__L2_N3), 
	.I(clk__L1_N0));
   bf01m40 clk__L2_I2 (.Z(clk__L2_N2), 
	.I(clk__L1_N0));
   bf01m40 clk__L2_I1 (.Z(clk__L2_N1), 
	.I(clk__L1_N0));
   bf01m40 clk__L2_I0 (.Z(clk__L2_N0), 
	.I(clk__L1_N0));
   bf01m160 clk__L1_I0 (.Z(clk__L1_N0), 
	.I(clk));
   ff00s02 i_rx_phy_rxdn_s0_reg (.Q(i_rx_phy_rxdn_s0), 
	.D(rxdn), 
	.CP(clk__L2_N3));
   ff00s02 i_rx_phy_rxdn_s_r_reg (.Q(i_rx_phy_rxdn_s_r), 
	.D(i_rx_phy_N31), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_rxdp_s0_reg (.Q(i_rx_phy_rxdp_s0), 
	.D(rxdp), 
	.CP(clk__L2_N3));
   ff00s02 i_rx_phy_rxdp_s_r_reg (.Q(i_rx_phy_rxdp_s_r), 
	.D(i_rx_phy_N29), 
	.CP(clk__L2_N2));
   ff00s02 i_rx_phy_se0_r_reg (.QN(n498), 
	.D(n706), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_rxd_s0_reg (.QN(n443), 
	.Q(i_rx_phy_rxd_s0), 
	.D(rxd), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_rxd_s1_reg (.QN(n459), 
	.Q(i_rx_phy_rxd_s1), 
	.D(i_rx_phy_rxd_s0), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_fs_ce_r1_reg (.Q(i_rx_phy_fs_ce_r1), 
	.D(n299), 
	.CP(clk__L2_N2));
   ff00s02 i_rx_phy_fs_ce_r2_reg (.Q(i_rx_phy_fs_ce_r2), 
	.D(i_rx_phy_fs_ce_r1), 
	.CP(clk__L2_N1));
   ff00s02 i_tx_phy_hold_reg_d_reg_1_ (.QN(n470), 
	.D(i_tx_phy_hold_reg[1]), 
	.CP(clk__L2_N0));
   ff00s02 i_tx_phy_hold_reg_d_reg_3_ (.QN(n471), 
	.D(i_tx_phy_hold_reg[3]), 
	.CP(clk__L2_N0));
   ff00s02 i_tx_phy_hold_reg_d_reg_5_ (.Q(i_tx_phy_hold_reg_d[5]), 
	.D(i_tx_phy_hold_reg[5]), 
	.CP(clk__L2_N1));
   ff00s02 i_tx_phy_hold_reg_d_reg_7_ (.QN(n472), 
	.D(i_tx_phy_hold_reg[7]), 
	.CP(clk__L2_N0));
   ff00s02 i_tx_phy_TxReady_o_reg (.Q(TxReady_o), 
	.D(i_tx_phy_N29), 
	.CP(clk__L2_N2));
   ff00s02 i_rx_phy_rx_valid_reg (.Q(RxValid_o), 
	.D(i_rx_phy_N149), 
	.CP(clk__L2_N2));
   ff00s02 i_rx_phy_bit_stuff_err_reg (.QN(n438), 
	.D(i_rx_phy_N127), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_byte_err_reg (.QN(n445), 
	.D(n366), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_sync_err_reg (.QN(n489), 
	.D(i_rx_phy_N25), 
	.CP(clk__L2_N1));
   ff00s02 i_rx_phy_sd_r_reg (.QN(n458), 
	.Q(i_rx_phy_sd_r), 
	.D(n235), 
	.CP(clk__L2_N2));
   ff00s02 i_tx_phy_append_eop_sync1_reg (.QN(n464), 
	.Q(i_tx_phy_append_eop_sync1), 
	.D(n219), 
	.CP(clk__L2_N2));
   ff00s02 i_tx_phy_append_eop_sync4_reg (.QN(n475), 
	.Q(i_tx_phy_append_eop_sync4), 
	.D(n216), 
	.CP(clk__L2_N2));
   ff00s02 i_tx_phy_tx_ip_reg (.QN(n473), 
	.Q(i_tx_phy_tx_ip), 
	.D(n215), 
	.CP(clk__L2_N2));
   ff00s02 i_tx_phy_txoe_r1_reg (.QN(n442), 
	.Q(i_tx_phy_txoe_r1), 
	.D(n213), 
	.CP(clk__L2_N1));
   ff00s02 i_tx_phy_txoe_r2_reg (.QN(n460), 
	.Q(i_tx_phy_txoe_r2), 
	.D(n212), 
	.CP(clk__L2_N1));
   ff00s02 i_tx_phy_txoe_reg (.QN(n174), 
	.Q(txoe), 
	.D(n211), 
	.CP(clk__L2_N1));
   ff00s02 i_tx_phy_sd_nrzi_o_reg (.QN(n467), 
	.Q(i_tx_phy_sd_nrzi_o), 
	.D(n210), 
	.CP(clk__L2_N2));
   ff00s02 i_tx_phy_hold_reg_reg_7_ (.QN(n469), 
	.Q(i_tx_phy_hold_reg[7]), 
	.D(n198), 
	.CP(clk__L2_N0));
   ff00s02 i_tx_phy_txdp_reg (.QN(n172), 
	.Q(txdp), 
	.D(n197), 
	.CP(clk__L2_N3));
   ff00s02 i_rx_phy_rx_valid_r_reg (.Q(i_rx_phy_rx_valid_r), 
	.D(n191), 
	.CP(clk__L2_N0));
   ff00f06 i_rx_phy_one_cnt_reg_0_ (.QN(n318), 
	.Q(i_rx_phy_one_cnt_0_), 
	.D(n187), 
	.CP(clk__L2_N2));
   ff00f06 i_rx_phy_fs_ce_reg (.QN(n535), 
	.Q(fs_ce), 
	.D(i_rx_phy_fs_ce_r2), 
	.CP(clk__L2_N1));
   ff00m02 i_tx_phy_hold_reg_d_reg_6_ (.QN(n499), 
	.D(i_tx_phy_hold_reg[6]), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_hold_reg_d_reg_4_ (.Q(i_tx_phy_hold_reg_d[4]), 
	.D(i_tx_phy_hold_reg[4]), 
	.CP(clk__L2_N0));
   ff00s02 i_tx_phy_hold_reg_d_reg_2_ (.QN(n494), 
	.D(i_tx_phy_hold_reg[2]), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_one_cnt_reg_2_ (.QN(n308), 
	.Q(i_tx_phy_one_cnt_2_), 
	.D(n223), 
	.CP(clk__L2_N2));
   ff00m02 i_rx_phy_rx_active_reg (.QN(n476), 
	.Q(n709), 
	.D(n708), 
	.CP(clk__L2_N0));
   ff00m02 rst_cnt_reg_1_ (.QN(n488), 
	.Q(rst_cnt[1]), 
	.D(n232), 
	.CP(clk__L2_N3));
   ff00s02 i_tx_phy_hold_reg_d_reg_0_ (.Q(i_tx_phy_hold_reg_d[0]), 
	.D(i_tx_phy_hold_reg[0]), 
	.CP(clk__L2_N0));
   ff00m02 usb_rst_reg (.QN(n171), 
	.Q(usb_rst), 
	.D(N23), 
	.CP(clk__L2_N3));
   ff00m02 i_rx_phy_bit_cnt_reg_0_ (.QN(n315), 
	.Q(i_rx_phy_bit_cnt_0_), 
	.D(n176), 
	.CP(clk__L2_N3));
   ff00m02 i_rx_phy_bit_cnt_reg_1_ (.QN(n449), 
	.Q(i_rx_phy_bit_cnt_1_), 
	.D(n175), 
	.CP(clk__L2_N3));
   ff00m02 i_rx_phy_fs_state_reg_1_ (.QN(n462), 
	.Q(i_rx_phy_fs_state_1_), 
	.D(n196), 
	.CP(clk__L2_N0));
   ff00m02 rst_cnt_reg_3_ (.QN(n316), 
	.Q(rst_cnt[3]), 
	.D(n230), 
	.CP(clk__L2_N3));
   ff00m02 i_tx_phy_ld_data_reg (.QN(n441), 
	.Q(i_tx_phy_ld_data), 
	.D(n705), 
	.CP(clk__L2_N1));
   ff00m02 i_rx_phy_rx_valid1_reg (.Q(i_rx_phy_rx_valid1), 
	.D(n192), 
	.CP(clk__L2_N3));
   ff00m02 i_tx_phy_hold_reg_reg_4_ (.QN(n323), 
	.Q(i_tx_phy_hold_reg[4]), 
	.D(n201), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_hold_reg_reg_3_ (.QN(n321), 
	.Q(i_tx_phy_hold_reg[3]), 
	.D(n202), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_hold_reg_reg_2_ (.QN(n320), 
	.Q(i_tx_phy_hold_reg[2]), 
	.D(n203), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_hold_reg_reg_1_ (.QN(n322), 
	.Q(i_tx_phy_hold_reg[1]), 
	.D(n204), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_hold_reg_reg_0_ (.QN(n319), 
	.Q(i_tx_phy_hold_reg[0]), 
	.D(n225), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_hold_reg_reg_6_ (.QN(n493), 
	.Q(i_tx_phy_hold_reg[6]), 
	.D(n199), 
	.CP(clk__L2_N0));
   ff00m02 i_rx_phy_hold_reg_reg_7_ (.QN(n492), 
	.Q(DataIn_o[7]), 
	.D(n184), 
	.CP(clk__L2_N3));
   ff00m02 rst_cnt_reg_2_ (.QN(n317), 
	.Q(rst_cnt[2]), 
	.D(n231), 
	.CP(clk__L2_N2));
   ff00m02 i_rx_phy_hold_reg_reg_2_ (.QN(n486), 
	.Q(DataIn_o[2]), 
	.D(n179), 
	.CP(clk__L2_N3));
   ff00m02 i_rx_phy_hold_reg_reg_4_ (.QN(n484), 
	.Q(DataIn_o[4]), 
	.D(n181), 
	.CP(clk__L2_N3));
   ff00m02 i_rx_phy_hold_reg_reg_5_ (.QN(n483), 
	.Q(DataIn_o[5]), 
	.D(n182), 
	.CP(clk__L2_N3));
   ff00m02 i_rx_phy_hold_reg_reg_6_ (.QN(n482), 
	.Q(DataIn_o[6]), 
	.D(n183), 
	.CP(clk__L2_N3));
   ff00m02 rst_cnt_reg_4_ (.QN(n456), 
	.Q(rst_cnt[4]), 
	.D(n229), 
	.CP(clk__L2_N3));
   ff00m02 i_tx_phy_sft_done_r_reg (.QN(n324), 
	.Q(i_tx_phy_sft_done_r), 
	.D(i_tx_phy_sft_done), 
	.CP(clk__L2_N2));
   ff00m02 i_tx_phy_bit_cnt_reg_2_ (.QN(n439), 
	.Q(i_tx_phy_bit_cnt_2_), 
	.D(n221), 
	.CP(clk__L2_N1));
   ff00m02 i_tx_phy_sd_raw_o_reg (.QN(n478), 
	.D(n252), 
	.CP(clk__L2_N1));
   ff00m02 i_rx_phy_dpll_state_reg_1_ (.QN(n457), 
	.D(n702), 
	.CP(clk__L2_N1));
   ff00m02 i_rx_phy_dpll_state_reg_0_ (.QN(n452), 
	.Q(i_rx_phy_dpll_state_0_), 
	.D(i_rx_phy_N34), 
	.CP(clk__L2_N1));
   ff00m02 i_rx_phy_bit_cnt_reg_2_ (.QN(n440), 
	.Q(i_rx_phy_bit_cnt_2_), 
	.D(n193), 
	.CP(clk__L2_N3));
   ff00m02 i_tx_phy_append_eop_reg (.QN(n444), 
	.D(n220), 
	.CP(clk__L2_N2));
   ff00m02 i_tx_phy_txdn_reg (.QN(n173), 
	.Q(txdn), 
	.D(n209), 
	.CP(clk__L2_N2));
   ff00f03 i_tx_phy_state_reg_0_ (.QN(n468), 
	.Q(i_tx_phy_state_0_), 
	.D(n228), 
	.CP(clk__L2_N3));
   ff00f02 i_rx_phy_fs_state_reg_0_ (.QN(n450), 
	.Q(i_rx_phy_fs_state_0_), 
	.D(n189), 
	.CP(clk__L2_N0));
   ff00f02 i_rx_phy_fs_state_reg_2_ (.QN(n490), 
	.Q(i_rx_phy_fs_state_2_), 
	.D(n195), 
	.CP(clk__L2_N0));
   ff00f02 i_rx_phy_rxdn_s_reg (.QN(n497), 
	.Q(i_rx_phy_rxdn_s), 
	.D(i_rx_phy_N32), 
	.CP(clk__L2_N0));
   ff00f02 i_rx_phy_shift_en_reg (.QN(n496), 
	.Q(i_rx_phy_shift_en), 
	.D(n194), 
	.CP(clk__L2_N2));
   ff00f02 i_rx_phy_rx_en_reg (.QN(n453), 
	.Q(i_rx_phy_rx_en), 
	.D(txoe), 
	.CP(clk__L2_N1));
   ff00f02 i_rx_phy_one_cnt_reg_2_ (.QN(n474), 
	.Q(i_rx_phy_one_cnt_2_), 
	.D(n185), 
	.CP(clk__L2_N2));
   ff00f02 i_tx_phy_data_done_reg (.QN(n463), 
	.Q(i_tx_phy_data_done), 
	.D(n205), 
	.CP(clk__L2_N2));
   ff00f02 i_rx_phy_rxd_s_reg (.QN(n314), 
	.Q(i_rx_phy_rxd_s), 
	.D(n236), 
	.CP(clk__L2_N1));
   ff00f02 i_rx_phy_rxdp_s1_reg (.QN(n495), 
	.Q(LineState_o[0]), 
	.D(i_rx_phy_rxdp_s0), 
	.CP(clk__L2_N3));
   ff00f02 i_tx_phy_one_cnt_reg_1_ (.QN(n465), 
	.Q(i_tx_phy_one_cnt_1_), 
	.D(n207), 
	.CP(clk__L2_N2));
   ff00f02 i_rx_phy_rxd_r_reg (.QN(n481), 
	.Q(i_rx_phy_rxd_r), 
	.D(n533), 
	.CP(clk__L2_N1));
   ff00m06 i_tx_phy_bit_cnt_reg_0_ (.QN(n448), 
	.Q(i_tx_phy_bit_cnt_0_), 
	.D(n206), 
	.CP(clk__L2_N0));
   ff00m03 i_tx_phy_bit_cnt_reg_1_ (.QN(n536), 
	.Q(i_tx_phy_bit_cnt_1_), 
	.D(n703), 
	.CP(clk__L2_N0));
   ff00m06 i_tx_phy_append_eop_sync3_reg (.QN(n436), 
	.Q(i_tx_phy_append_eop_sync3), 
	.D(n217), 
	.CP(clk__L2_N3));
   ff00f02 i_rx_phy_rxdp_s_reg (.QN(n447), 
	.Q(i_rx_phy_rxdp_s), 
	.D(i_rx_phy_N30), 
	.CP(clk__L2_N0));
   ff00f03 i_tx_phy_state_reg_1_ (.QN(n451), 
	.Q(i_tx_phy_state_1_), 
	.D(n226), 
	.CP(clk__L2_N3));
   ff00f02 i_tx_phy_state_reg_2_ (.QN(n302), 
	.Q(i_tx_phy_state_2_), 
	.D(n227), 
	.CP(clk__L2_N3));
   ff00m06 i_tx_phy_sft_done_reg (.Q(i_tx_phy_sft_done), 
	.D(n704), 
	.CP(clk__L2_N2));
   ff00m02 i_rx_phy_sd_nrzi_reg (.QN(n455), 
	.Q(i_rx_phy_sd_nrzi), 
	.D(n188), 
	.CP(clk__L2_N2));
   ff00m03 i_rx_phy_one_cnt_reg_1_ (.QN(n491), 
	.Q(i_rx_phy_one_cnt_1_), 
	.D(n186), 
	.CP(clk__L2_N2));
   ff00s02 i_rx_phy_hold_reg_reg_3_ (.QN(n485), 
	.Q(DataIn_o[3]), 
	.D(n180), 
	.CP(clk__L2_N3));
   ff00s03 i_rx_phy_hold_reg_reg_1_ (.QN(n487), 
	.Q(DataIn_o[1]), 
	.D(n178), 
	.CP(clk__L2_N3));
   ff00s02 i_rx_phy_hold_reg_reg_0_ (.QN(n480), 
	.Q(DataIn_o[0]), 
	.D(n177), 
	.CP(clk__L2_N3));
   ff00m02 rst_cnt_reg_0_ (.QN(n461), 
	.Q(rst_cnt[0]), 
	.D(n233), 
	.CP(clk__L2_N2));
   ff00m03 i_tx_phy_tx_ip_sync_reg (.QN(n437), 
	.Q(i_tx_phy_tx_ip_sync), 
	.D(n214), 
	.CP(clk__L2_N1));
   ff00s06 i_tx_phy_append_eop_sync2_reg (.Q(i_tx_phy_append_eop_sync2), 
	.D(n218), 
	.CP(clk__L2_N2));
   ff00m03 i_tx_phy_one_cnt_reg_0_ (.QN(n454), 
	.Q(i_tx_phy_one_cnt_0_), 
	.D(n208), 
	.CP(clk__L2_N1));
   ff00m02 i_tx_phy_hold_reg_reg_5_ (.QN(n479), 
	.Q(i_tx_phy_hold_reg[5]), 
	.D(n200), 
	.CP(clk__L2_N1));
   ff00m03 i_rx_phy_se0_s_reg (.QN(n466), 
	.Q(i_rx_phy_se0_s), 
	.D(n234), 
	.CP(clk__L2_N0));
   ff00m02 i_tx_phy_sd_bs_o_reg (.QN(n477), 
	.D(n224), 
	.CP(clk__L2_N1));
   ff00m02 i_rx_phy_rxdn_s1_reg (.QN(n446), 
	.Q(LineState_o[1]), 
	.D(i_rx_phy_rxdn_s0), 
	.CP(clk__L2_N3));
   in01s02 U319 (.ZN(n617), 
	.I(i_rx_phy_rxd_s));
   in01s02 U320 (.ZN(n402), 
	.I(i_rx_phy_se0_s));
   in01s01 U321 (.ZN(n626), 
	.I(n649));
   na03s02 U322 (.Z(n573), 
	.A3(rst), 
	.A2(i_tx_phy_one_cnt_1_), 
	.A1(n454));
   oa22s01 U323 (.ZN(n584), 
	.B2(n500), 
	.B1(n581), 
	.A2(n448), 
	.A1(n355));
   na02s02 U324 (.Z(n583), 
	.A2(n582), 
	.A1(n500));
   in01s01 U325 (.ZN(n560), 
	.I(n587));
   na02s02 U326 (.Z(n613), 
	.A2(rst), 
	.A1(i_rx_phy_one_cnt_2_));
   in01s01 U327 (.ZN(n353), 
	.I(i_rx_phy_rxdn_s));
   na02f01 U328 (.Z(n695), 
	.A2(n391), 
	.A1(n392));
   na02f01 U329 (.Z(n391), 
	.A2(n446), 
	.A1(n171));
   na02f02 U330 (.Z(n343), 
	.A2(n316), 
	.A1(n701));
   na03m01 U331 (.Z(n701), 
	.A3(rst_cnt[0]), 
	.A2(rst_cnt[2]), 
	.A1(rst_cnt[1]));
   in01s02 U332 (.ZN(n306), 
	.I(n461));
   na02f02 U333 (.Z(n433), 
	.A2(n434), 
	.A1(n390));
   na03f02 U334 (.Z(n325), 
	.A3(n358), 
	.A2(i_tx_phy_state_0_), 
	.A1(n451));
   in01s03 U335 (.ZN(n358), 
	.I(i_tx_phy_state_2_));
   na02f01 U336 (.Z(n514), 
	.A2(i_rx_phy_sd_nrzi), 
	.A1(RxActive_o));
   in01s01 U337 (.ZN(n389), 
	.I(n665));
   na02m02 U338 (.Z(n337), 
	.A2(n358), 
	.A1(n468));
   in01s01 U339 (.ZN(n516), 
	.I(n517));
   na02s01 U340 (.Z(n670), 
	.A2(rst), 
	.A1(i_tx_phy_tx_ip_sync));
   in01s01 U341 (.ZN(n217), 
	.I(n596));
   in01s02 U342 (.ZN(n350), 
	.I(i_tx_phy_append_eop_sync3));
   oa21s02 U343 (.ZN(n226), 
	.B(n363), 
	.A2(n359), 
	.A1(n354));
   in01s01 U344 (.ZN(n354), 
	.I(i_tx_phy_state_1_));
   in01s01 U345 (.ZN(n359), 
	.I(n604));
   in01s01 U346 (.ZN(n363), 
	.I(n364));
   na02f01 U347 (.Z(n364), 
	.A2(n360), 
	.A1(n325));
   in01s01 U348 (.ZN(n357), 
	.I(n551));
   na04m01 U349 (.Z(n551), 
	.A4(rst), 
	.A3(i_tx_phy_state_1_), 
	.A2(i_tx_phy_state_0_), 
	.A1(i_tx_phy_append_eop_sync3));
   in01s01 U350 (.ZN(n591), 
	.I(n500));
   in01s01 U351 (.ZN(n188), 
	.I(n621));
   in01s01 U352 (.ZN(n631), 
	.I(n397));
   in01s01 U353 (.ZN(n630), 
	.I(n624));
   in01s01 U354 (.ZN(RxActive_o), 
	.I(n368));
   in01s01 U355 (.ZN(n336), 
	.I(i_tx_phy_data_done));
   in01s01 U356 (.ZN(n309), 
	.I(n308));
   in01f01 U357 (.ZN(n605), 
	.I(n333));
   na02s02 U358 (.Z(n380), 
	.A2(rst), 
	.A1(i_tx_phy_state_1_));
   na02m01 U359 (.Z(n360), 
	.A2(rst), 
	.A1(n333));
   in01s08 U360 (.ZN(n303), 
	.I(n304));
   in01s01 U361 (.ZN(n565), 
	.I(n589));
   na03s01 U362 (.Z(n627), 
	.A3(i_rx_phy_sd_nrzi), 
	.A2(rst), 
	.A1(n318));
   or02m02 U363 (.Z(n522), 
	.A2(i_rx_phy_se0_s), 
	.A1(n706));
   na02m01 U364 (.Z(n432), 
	.A2(i_rx_phy_bit_cnt_2_), 
	.A1(n433));
   oa21s01 U365 (.ZN(n682), 
	.B(n355), 
	.A2(n171), 
	.A1(n356));
   in01s04 U366 (.ZN(n384), 
	.I(n706));
   ao22f01 U367 (.ZN(n431), 
	.B2(n331), 
	.B1(n432), 
	.A2(i_rx_phy_rx_valid1), 
	.A1(n435));
   oa21s01 U368 (.ZN(n637), 
	.B(rst), 
	.A2(n636), 
	.A1(n648));
   in01s01 U369 (.ZN(n533), 
	.I(n314));
   oa21f02 U370 (.ZN(n178), 
	.B(n658), 
	.A2(n313), 
	.A1(n487));
   in01f01 U371 (.ZN(n428), 
	.I(n496));
   na02f02 U372 (.Z(n706), 
	.A2(n353), 
	.A1(n447));
   in01f01 U373 (.ZN(n344), 
	.I(n325));
   in01s01 U374 (.ZN(n506), 
	.I(n543));
   na02f01 U375 (.Z(n684), 
	.A2(n446), 
	.A1(n495));
   na02s06 U376 (.Z(n542), 
	.A2(n545), 
	.A1(n506));
   na02s02 U377 (.Z(n425), 
	.A2(DataIn_o[3]), 
	.A1(n660));
   na02f01 U378 (.Z(n577), 
	.A2(n521), 
	.A1(n513));
   in01s01 U379 (.ZN(n629), 
	.I(n625));
   in01s01 U380 (.ZN(n532), 
	.I(n646));
   in01s01 U381 (.ZN(n393), 
	.I(n622));
   oa21s01 U382 (.ZN(n607), 
	.B(rst), 
	.A2(n606), 
	.A1(n526));
   oa22f01 U383 (.ZN(n209), 
	.B2(n676), 
	.B1(n534), 
	.A2(n173), 
	.A1(n355));
   oa21f02 U384 (.ZN(n177), 
	.B(n659), 
	.A2(n312), 
	.A1(n480));
   na03s01 U385 (.Z(N23), 
	.A3(rst_cnt[3]), 
	.A2(rst_cnt[4]), 
	.A1(n701));
   in01s01 U386 (.ZN(RxError_o), 
	.I(n666));
   oa21f01 U387 (.ZN(n677), 
	.B(i_tx_phy_sd_nrzi_o), 
	.A2(n707), 
	.A1(n436));
   ao22f02 U388 (.ZN(n688), 
	.B2(n686), 
	.B1(n349), 
	.A2(n687), 
	.A1(n693));
   oa21f02 U389 (.ZN(n232), 
	.B(n688), 
	.A2(n689), 
	.A1(n690));
   oa22f01 U390 (.ZN(n204), 
	.B2(n558), 
	.B1(n322), 
	.A2(n525), 
	.A1(n555));
   na02f02 U391 (.Z(n696), 
	.A2(n343), 
	.A1(n695));
   in01f01 U392 (.ZN(n368), 
	.I(n709));
   ao21f01 U393 (.ZN(n223), 
	.B(n578), 
	.A2(n521), 
	.A1(n579));
   na03f03 U394 (.Z(n530), 
	.A3(n466), 
	.A2(n384), 
	.A1(n385));
   or02f03 U395 (.Z(n639), 
	.A2(n535), 
	.A1(n709));
   in01f02 U396 (.ZN(n176), 
	.I(n616));
   ao21f02 U397 (.ZN(n377), 
	.B(n614), 
	.A2(n315), 
	.A1(n612));
   oa21f01 U398 (.ZN(n650), 
	.B(n521), 
	.A2(n649), 
	.A1(n455));
   na03f01 U399 (.Z(n185), 
	.A3(n651), 
	.A2(n428), 
	.A1(n650));
   na02f02 U400 (.Z(i_rx_phy_N127), 
	.A2(n414), 
	.A1(n661));
   na02f03 U401 (.Z(n507), 
	.A2(n510), 
	.A1(n508));
   ao21f01 U402 (.ZN(n628), 
	.B(n417), 
	.A2(n626), 
	.A1(n627));
   in01f04 U403 (.ZN(n326), 
	.I(n349));
   oa22f01 U404 (.ZN(n231), 
	.B2(n326), 
	.B1(n327), 
	.A2(n329), 
	.A1(n317));
   or02f01 U405 (.Z(n572), 
	.A2(i_tx_phy_one_cnt_0_), 
	.A1(n534));
   oa22f01 U406 (.ZN(n208), 
	.B2(n608), 
	.B1(n454), 
	.A2(n352), 
	.A1(n572));
   oa21f01 U407 (.ZN(n546), 
	.B(n544), 
	.A2(n453), 
	.A1(n545));
   or02f02 U408 (.Z(n548), 
	.A2(i_rx_phy_dpll_state_0_), 
	.A1(n546));
   ao21f01 U409 (.ZN(n597), 
	.B(n302), 
	.A2(n303), 
	.A1(n379));
   na03f03 U410 (.Z(n304), 
	.A3(n539), 
	.A2(rst), 
	.A1(n468));
   in01f02 U411 (.ZN(n659), 
	.I(n332));
   na02f03 U412 (.Z(n660), 
	.A2(n330), 
	.A1(n331));
   na02f01 U413 (.Z(n328), 
	.A2(n317), 
	.A1(n694));
   na03f03 U414 (.Z(n189), 
	.A3(rst), 
	.A2(n640), 
	.A1(n645));
   or02f02 U415 (.Z(n525), 
	.A2(n441), 
	.A1(n526));
   ao21f01 U416 (.ZN(n365), 
	.B(n437), 
	.A2(n568), 
	.A1(n567));
   oa21f03 U417 (.ZN(n604), 
	.B(n507), 
	.A2(n344), 
	.A1(n509));
   ao21f02 U418 (.ZN(n527), 
	.B(n411), 
	.A2(n412), 
	.A1(n530));
   oa21f03 U419 (.ZN(n195), 
	.B(n527), 
	.A2(n531), 
	.A1(n532));
   oa21f01 U420 (.ZN(n585), 
	.B(i_tx_phy_tx_ip_sync), 
	.A2(n583), 
	.A1(n584));
   or02f01 U421 (.Z(n644), 
	.A2(i_rx_phy_fs_state_1_), 
	.A1(n490));
   na02f03 U422 (.Z(n422), 
	.A2(DataIn_o[6]), 
	.A1(n313));
   na02f03 U423 (.Z(n397), 
	.A2(n331), 
	.A1(n398));
   na03f02 U424 (.Z(n335), 
	.A3(n336), 
	.A2(n348), 
	.A1(n598));
   na02f01 U425 (.Z(n503), 
	.A2(n171), 
	.A1(n427));
   na02f03 U426 (.Z(n405), 
	.A2(n406), 
	.A1(n407));
   na02f01 U427 (.Z(n502), 
	.A2(n699), 
	.A1(n701));
   in01f04 U428 (.ZN(n331), 
	.I(n662));
   oa21f01 U429 (.ZN(n383), 
	.B(n530), 
	.A2(n386), 
	.A1(n389));
   oa21f03 U430 (.ZN(n180), 
	.B(n656), 
	.A2(n312), 
	.A1(n485));
   oa21f03 U431 (.ZN(n179), 
	.B(n657), 
	.A2(n312), 
	.A1(n486));
   in01f08 U432 (.ZN(n539), 
	.I(fs_ce));
   in01f02 U433 (.ZN(n252), 
	.I(n571));
   na02f02 U434 (.Z(n561), 
	.A2(n537), 
	.A1(n494));
   oa21f02 U435 (.ZN(n230), 
	.B(n697), 
	.A2(n700), 
	.A1(n316));
   oa21f03 U436 (.ZN(n632), 
	.B(n377), 
	.A2(n496), 
	.A1(n378));
   oa22f03 U437 (.ZN(n196), 
	.B2(n531), 
	.B1(n643), 
	.A2(n538), 
	.A1(n511));
   na02f03 U438 (.Z(n400), 
	.A2(n401), 
	.A1(n384));
   in01f01 U439 (.ZN(n192), 
	.I(n431));
   oa21f03 U440 (.ZN(n347), 
	.B(n344), 
	.A2(n345), 
	.A1(n336));
   na02f03 U441 (.Z(n576), 
	.A2(i_tx_phy_one_cnt_2_), 
	.A1(i_tx_phy_one_cnt_1_));
   oa22f02 U442 (.ZN(n703), 
	.B2(n437), 
	.B1(n588), 
	.A2(n408), 
	.A1(n437));
   oa22f02 U443 (.ZN(n207), 
	.B2(n575), 
	.B1(n669), 
	.A2(n608), 
	.A1(n465));
   na02f02 U444 (.Z(n587), 
	.A2(i_tx_phy_bit_cnt_0_), 
	.A1(n536));
   na02f03 U445 (.Z(n333), 
	.A2(i_tx_phy_sft_done), 
	.A1(n334));
   oa22f02 U446 (.ZN(n187), 
	.B2(n355), 
	.B1(n393), 
	.A2(n394), 
	.A1(n395));
   na02f02 U447 (.Z(n623), 
	.A2(i_rx_phy_sd_nrzi), 
	.A1(n318));
   na02f03 U448 (.Z(n589), 
	.A2(i_tx_phy_bit_cnt_0_), 
	.A1(i_tx_phy_bit_cnt_1_));
   na02f03 U449 (.Z(n221), 
	.A2(n338), 
	.A1(n339));
   na02f03 U450 (.Z(n417), 
	.A2(rst), 
	.A1(n539));
   na03f03 U451 (.Z(n648), 
	.A3(i_rx_phy_rx_en), 
	.A2(n404), 
	.A1(n405));
   ao22f02 U452 (.ZN(n418), 
	.B2(n419), 
	.B1(n397), 
	.A2(i_rx_phy_bit_cnt_1_), 
	.A1(n632));
   in01f01 U453 (.ZN(n175), 
	.I(n418));
   na02f03 U454 (.Z(n349), 
	.A2(n391), 
	.A1(n392));
   oa22f02 U455 (.ZN(n233), 
	.B2(n689), 
	.B1(n683), 
	.A2(n306), 
	.A1(n326));
   or02f01 U456 (.Z(n674), 
	.A2(n707), 
	.A1(i_tx_phy_append_eop_sync3));
   na02f03 U457 (.Z(n330), 
	.A2(n427), 
	.A1(i_rx_phy_shift_en));
   na02f03 U458 (.Z(n312), 
	.A2(n330), 
	.A1(n331));
   oa21f03 U459 (.ZN(n181), 
	.B(n655), 
	.A2(n313), 
	.A1(n484));
   na02f03 U460 (.Z(n541), 
	.A2(i_rx_phy_rxd_s), 
	.A1(n481));
   na02f03 U461 (.Z(n399), 
	.A2(rst), 
	.A1(i_rx_phy_shift_en));
   oa22f02 U462 (.ZN(n186), 
	.B2(n629), 
	.B1(n628), 
	.A2(n630), 
	.A1(n631));
   or02f01 U463 (.Z(n371), 
	.A2(n453), 
	.A1(n542));
   or03f01 U464 (.Z(n194), 
	.A3(n648), 
	.A2(n415), 
	.A1(n416));
   na02f03 U465 (.Z(n543), 
	.A2(i_rx_phy_rxd_r), 
	.A1(n617));
   na03f03 U466 (.Z(n615), 
	.A3(n318), 
	.A2(n372), 
	.A1(n613));
   in01f02 U467 (.ZN(n656), 
	.I(n424));
   in01f02 U468 (.ZN(n657), 
	.I(n425));
   na02f01 U469 (.Z(n426), 
	.A2(DataIn_o[2]), 
	.A1(n660));
   oa21f02 U470 (.ZN(n183), 
	.B(n653), 
	.A2(n312), 
	.A1(n482));
   na03f03 U471 (.Z(n662), 
	.A3(i_rx_phy_one_cnt_1_), 
	.A2(i_rx_phy_one_cnt_2_), 
	.A1(n318));
   na03f01 U472 (.Z(n228), 
	.A3(n602), 
	.A2(n603), 
	.A1(n604));
   ao22f02 U473 (.ZN(n408), 
	.B2(n409), 
	.B1(n500), 
	.A2(n410), 
	.A1(n591));
   na02f03 U474 (.Z(n663), 
	.A2(i_rx_phy_rx_en), 
	.A1(n497));
   ao21f02 U475 (.ZN(n700), 
	.B(n692), 
	.A2(n693), 
	.A1(n317));
   oa21f01 U476 (.ZN(n229), 
	.B(n501), 
	.A2(n700), 
	.A1(n456));
   oa22f02 U477 (.ZN(n566), 
	.B2(n563), 
	.B1(n564), 
	.A2(n472), 
	.A1(n565));
   oa21f01 U478 (.ZN(n571), 
	.B(n365), 
	.A2(n569), 
	.A1(n570));
   na02f03 U479 (.Z(n500), 
	.A2(n454), 
	.A1(n576));
   na03f03 U480 (.Z(n361), 
	.A3(rst), 
	.A2(n362), 
	.A1(n495));
   ao22f03 U481 (.ZN(n508), 
	.B2(n436), 
	.B1(n380), 
	.A2(n381), 
	.A1(n382));
   na02f03 U482 (.Z(n680), 
	.A2(rst), 
	.A1(fs_ce));
   oa21f03 U483 (.ZN(n645), 
	.B(n400), 
	.A2(n638), 
	.A1(n403));
   in01f01 U484 (.ZN(i_rx_phy_N25), 
	.I(n383));
   oa21f03 U485 (.ZN(n210), 
	.B(n671), 
	.A2(n672), 
	.A1(n673));
   or02f02 U486 (.Z(n558), 
	.A2(i_tx_phy_ld_data), 
	.A1(n526));
   na02f03 U487 (.Z(n526), 
	.A2(n337), 
	.A1(n600));
   oa21s03 U488 (.ZN(n198), 
	.B(n552), 
	.A2(i_tx_phy_ld_data), 
	.A1(n469));
   ao21s03 U489 (.ZN(n552), 
	.B(n526), 
	.A2(i_tx_phy_ld_data), 
	.A1(DataOut_i[7]));
   oa21s03 U490 (.ZN(n564), 
	.B(n448), 
	.A2(i_tx_phy_hold_reg_d[4]), 
	.A1(n537));
   or02s01 U491 (.Z(n305), 
	.A2(n318), 
	.A1(n491));
   na02s03 U492 (.Z(n381), 
	.A2(rst), 
	.A1(n535));
   ao21s03 U493 (.ZN(n220), 
	.B(n356), 
	.A2(n592), 
	.A1(n593));
   bf01m02 U494 (.Z(n372), 
	.I(i_rx_phy_one_cnt_1_));
   ao21s02 U495 (.ZN(n544), 
	.B(n356), 
	.A2(i_rx_phy_rx_en), 
	.A1(n543));
   na02s03 U496 (.Z(n307), 
	.A2(n413), 
	.A1(n663));
   in01f03 U497 (.ZN(n378), 
	.I(n615));
   in01m02 U498 (.ZN(n385), 
	.I(n639));
   oa22s02 U499 (.ZN(n201), 
	.B2(n323), 
	.B1(n558), 
	.A2(n525), 
	.A1(n554));
   oa22s02 U500 (.ZN(n202), 
	.B2(n321), 
	.B1(n558), 
	.A2(n556), 
	.A1(n525));
   oa22s02 U501 (.ZN(n225), 
	.B2(n319), 
	.B1(n558), 
	.A2(n559), 
	.A1(n525));
   oa22s02 U502 (.ZN(n199), 
	.B2(n493), 
	.B1(n558), 
	.A2(n553), 
	.A1(n525));
   in01f01 U503 (.ZN(n329), 
	.I(n692));
   oa21s01 U504 (.ZN(n501), 
	.B(n349), 
	.A2(n698), 
	.A1(n502));
   oa21s02 U505 (.ZN(n616), 
	.B(n632), 
	.A2(n634), 
	.A1(i_rx_phy_bit_cnt_0_));
   oa22s02 U506 (.ZN(n203), 
	.B2(n320), 
	.B1(n558), 
	.A2(n525), 
	.A1(n557));
   na02s02 U507 (.Z(n430), 
	.A2(n521), 
	.A1(n589));
   in01s01 U508 (.ZN(n342), 
	.I(n539));
   or02s01 U509 (.Z(n379), 
	.A2(i_tx_phy_state_0_), 
	.A1(n350));
   na02s02 U510 (.Z(n406), 
	.A2(i_rx_phy_fs_state_0_), 
	.A1(fs_ce));
   na02s02 U511 (.Z(n407), 
	.A2(i_rx_phy_fs_state_2_), 
	.A1(i_rx_phy_rxdn_s));
   na02s01 U512 (.Z(n686), 
	.A2(n306), 
	.A1(n488));
   na02s01 U513 (.Z(n687), 
	.A2(rst_cnt[1]), 
	.A1(n461));
   na02s01 U514 (.Z(n574), 
	.A2(i_tx_phy_one_cnt_0_), 
	.A1(n465));
   oa21s01 U515 (.ZN(n236), 
	.B(n540), 
	.A2(n443), 
	.A1(n459));
   oa21s01 U516 (.ZN(n540), 
	.B(n533), 
	.A2(i_rx_phy_rxd_s1), 
	.A1(i_rx_phy_rxd_s0));
   na02s01 U517 (.Z(n299), 
	.A2(i_rx_phy_dpll_state_0_), 
	.A1(n457));
   in01s01 U518 (.ZN(n707), 
	.I(phy_tx_mode));
   na02s01 U519 (.Z(n667), 
	.A2(TxValid_i), 
	.A1(rst));
   na03s01 U520 (.Z(n666), 
	.A3(n438), 
	.A2(n445), 
	.A1(n489));
   in01s01 U521 (.ZN(n340), 
	.I(n670));
   na02s01 U522 (.Z(n698), 
	.A2(rst_cnt[4]), 
	.A1(n316));
   in01s01 U523 (.ZN(n327), 
	.I(n328));
   in01s01 U524 (.ZN(n553), 
	.I(DataOut_i[6]));
   in01s01 U525 (.ZN(n559), 
	.I(DataOut_i[0]));
   in01s01 U526 (.ZN(n555), 
	.I(DataOut_i[1]));
   in01s01 U527 (.ZN(n557), 
	.I(DataOut_i[2]));
   in01s01 U528 (.ZN(n556), 
	.I(DataOut_i[3]));
   in01s01 U529 (.ZN(n554), 
	.I(DataOut_i[4]));
   in01s01 U530 (.ZN(n643), 
	.I(n641));
   na02s01 U531 (.Z(n419), 
	.A2(n449), 
	.A1(i_rx_phy_bit_cnt_0_));
   ao21s02 U532 (.ZN(n603), 
	.B(n597), 
	.A2(n605), 
	.A1(n598));
   or02s01 U533 (.Z(i_rx_phy_N32), 
	.A2(i_rx_phy_rxdn_s_r), 
	.A1(i_rx_phy_N31));
   ao21s01 U534 (.ZN(n205), 
	.B(n549), 
	.A2(n463), 
	.A1(i_tx_phy_tx_ip));
   in01s01 U535 (.ZN(n549), 
	.I(n667));
   or02s01 U536 (.Z(n619), 
	.A2(i_rx_phy_sd_r), 
	.A1(n314));
   na02s01 U537 (.Z(n685), 
	.A2(rst_cnt[1]), 
	.A1(n684));
   ao21s01 U538 (.ZN(n636), 
	.B(n476), 
	.A2(n706), 
	.A1(i_rx_phy_rx_valid_r));
   or02s01 U539 (.Z(n579), 
	.A2(n576), 
	.A1(n478));
   na02s01 U540 (.Z(n704), 
	.A2(n590), 
	.A1(n591));
   or02s01 U541 (.Z(i_rx_phy_N30), 
	.A2(i_rx_phy_rxdp_s_r), 
	.A1(i_rx_phy_N29));
   oa21s01 U542 (.ZN(n234), 
	.B(n518), 
	.A2(n539), 
	.A1(n384));
   or02s01 U543 (.Z(n518), 
	.A2(n466), 
	.A1(n521));
   in01s01 U544 (.ZN(n394), 
	.I(n398));
   in01s01 U545 (.ZN(n191), 
	.I(n635));
   ao21s01 U546 (.ZN(n635), 
	.B(RxValid_o), 
	.A2(n539), 
	.A1(i_rx_phy_rx_valid_r));
   in01s01 U547 (.ZN(n550), 
	.I(DataOut_i[5]));
   na02s01 U548 (.Z(n671), 
	.A2(i_tx_phy_txoe_r1), 
	.A1(n670));
   na02s01 U549 (.Z(n672), 
	.A2(i_tx_phy_sd_nrzi_o), 
	.A1(n517));
   in01s01 U550 (.ZN(n610), 
	.I(n609));
   na02s01 U551 (.Z(n611), 
	.A2(n539), 
	.A1(n174));
   oa21s01 U552 (.ZN(n609), 
	.B(n521), 
	.A2(i_tx_phy_txoe_r2), 
	.A1(i_tx_phy_txoe_r1));
   or02s01 U553 (.Z(n592), 
	.A2(i_tx_phy_append_eop_sync2), 
	.A1(n444));
   or02s01 U554 (.Z(n668), 
	.A2(n477), 
	.A1(n355));
   oa21s01 U555 (.ZN(n235), 
	.B(n519), 
	.A2(n458), 
	.A1(n521));
   or02s01 U556 (.Z(n519), 
	.A2(n314), 
	.A1(n539));
   na02s01 U557 (.Z(i_rx_phy_N149), 
	.A2(n520), 
	.A1(n331));
   oa21s01 U558 (.ZN(n505), 
	.B(rst), 
	.A2(i_rx_phy_rx_en), 
	.A1(i_rx_phy_dpll_state_0_));
   na02s01 U559 (.Z(i_rx_phy_N29), 
	.A2(LineState_o[0]), 
	.A1(i_rx_phy_rxdp_s0));
   na02s01 U560 (.Z(i_rx_phy_N31), 
	.A2(LineState_o[1]), 
	.A1(i_rx_phy_rxdn_s0));
   in01s01 U561 (.ZN(n382), 
	.I(n358));
   in01m02 U562 (.ZN(n581), 
	.I(n580));
   oa21s02 U563 (.ZN(n338), 
	.B(n439), 
	.A2(n429), 
	.A1(n500));
   oa21s01 U564 (.ZN(n570), 
	.B(n439), 
	.A2(n470), 
	.A1(n560));
   in01m04 U565 (.ZN(n537), 
	.I(n536));
   na02s02 U566 (.Z(n598), 
	.A2(i_tx_phy_state_1_), 
	.A1(n468));
   na02s03 U567 (.Z(n313), 
	.A2(n330), 
	.A1(n331));
   oa21s06 U568 (.ZN(n184), 
	.B(n652), 
	.A2(n660), 
	.A1(n492));
   in01f06 U569 (.ZN(n652), 
	.I(n420));
   in01s01 U570 (.ZN(n356), 
	.I(rst));
   ao21s03 U571 (.ZN(n692), 
	.B(n691), 
	.A2(n694), 
	.A1(n503));
   na02s03 U572 (.Z(n332), 
	.A2(DataIn_o[1]), 
	.A1(n660));
   or02s01 U573 (.Z(n509), 
	.A2(n333), 
	.A1(n356));
   in01m02 U574 (.ZN(n334), 
	.I(i_tx_phy_sft_done_r));
   in01m02 U575 (.ZN(n593), 
	.I(n335));
   na02s03 U576 (.Z(n348), 
	.A2(n324), 
	.A1(i_tx_phy_sft_done));
   na02s03 U577 (.Z(n600), 
	.A2(TxValid_i), 
	.A1(n451));
   ao21s03 U578 (.ZN(n339), 
	.B(n340), 
	.A2(n591), 
	.A1(n341));
   na02s03 U579 (.Z(n341), 
	.A2(n342), 
	.A1(n590));
   na02s02 U580 (.Z(n590), 
	.A2(i_tx_phy_bit_cnt_2_), 
	.A1(n589));
   na02s03 U581 (.Z(n392), 
	.A2(n495), 
	.A1(n680));
   na03s03 U582 (.Z(n415), 
	.A3(i_rx_phy_fs_state_1_), 
	.A2(n404), 
	.A1(n405));
   in01m02 U583 (.ZN(n345), 
	.I(n598));
   na02s02 U584 (.Z(n705), 
	.A2(n348), 
	.A1(n347));
   na02s03 U585 (.Z(i_tx_phy_N29), 
	.A2(n346), 
	.A1(n347));
   na02s03 U586 (.Z(n346), 
	.A2(n667), 
	.A1(n348));
   na02s01 U587 (.Z(n409), 
	.A2(rst), 
	.A1(i_tx_phy_bit_cnt_1_));
   in01f03 U588 (.ZN(n691), 
	.I(n361));
   na02s01 U589 (.Z(n520), 
	.A2(n521), 
	.A1(i_rx_phy_rx_valid1));
   na02s02 U590 (.Z(n410), 
	.A2(n587), 
	.A1(n390));
   na02s02 U591 (.Z(n563), 
	.A2(n499), 
	.A1(i_tx_phy_bit_cnt_1_));
   or03s01 U592 (.Z(n351), 
	.A3(n500), 
	.A2(n478), 
	.A1(n437));
   or03s01 U593 (.Z(n352), 
	.A3(n500), 
	.A2(n478), 
	.A1(n437));
   or03s01 U594 (.Z(n669), 
	.A3(n500), 
	.A2(n478), 
	.A1(n437));
   na03s02 U595 (.Z(n614), 
	.A3(rst), 
	.A2(i_rx_phy_shift_en), 
	.A1(n539));
   in01m02 U596 (.ZN(n403), 
	.I(n450));
   in01f06 U597 (.ZN(n531), 
	.I(n645));
   oa21s03 U598 (.ZN(n640), 
	.B(n450), 
	.A2(n522), 
	.A1(n639));
   in01f03 U599 (.ZN(n429), 
	.I(n430));
   oa22s02 U600 (.ZN(n651), 
	.B2(n356), 
	.B1(n474), 
	.A2(n534), 
	.A1(n305));
   na03s01 U601 (.Z(n366), 
	.A3(n367), 
	.A2(n498), 
	.A1(n706));
   in01s02 U602 (.ZN(n524), 
	.I(n526));
   na02s02 U603 (.Z(n681), 
	.A2(n306), 
	.A1(n684));
   in01s01 U604 (.ZN(n369), 
	.I(i_rx_phy_bit_cnt_2_));
   na02s01 U605 (.Z(n641), 
	.A2(rst), 
	.A1(i_rx_phy_fs_state_1_));
   na02s03 U606 (.Z(n200), 
	.A2(n523), 
	.A1(n524));
   ao21s01 U607 (.ZN(n504), 
	.B(n505), 
	.A2(n452), 
	.A1(n542));
   or02s03 U608 (.Z(n608), 
	.A2(n437), 
	.A1(n355));
   in01s01 U609 (.ZN(n396), 
	.I(n623));
   in01m03 U610 (.ZN(n534), 
	.I(n390));
   in01m08 U611 (.ZN(n355), 
	.I(n417));
   in01m02 U612 (.ZN(n547), 
	.I(n299));
   na02s02 U613 (.Z(n694), 
	.A2(rst_cnt[0]), 
	.A1(rst_cnt[1]));
   na02s02 U614 (.Z(n434), 
	.A2(i_rx_phy_bit_cnt_1_), 
	.A1(i_rx_phy_bit_cnt_0_));
   in01f01 U615 (.ZN(n708), 
	.I(n637));
   oa21s02 U616 (.ZN(i_rx_phy_N34), 
	.B(n504), 
	.A2(n547), 
	.A1(n371));
   in01m02 U617 (.ZN(n697), 
	.I(n696));
   na02s02 U618 (.Z(n673), 
	.A2(n467), 
	.A1(n516));
   in01f01 U619 (.ZN(n215), 
	.I(n607));
   in01f01 U620 (.ZN(n689), 
	.I(n682));
   in01f01 U621 (.ZN(n416), 
	.I(n647));
   in01s02 U622 (.ZN(n511), 
	.I(n512));
   in01f01 U623 (.ZN(n435), 
	.I(n634));
   na02s02 U624 (.Z(n517), 
	.A2(n521), 
	.A1(n477));
   na02s02 U625 (.Z(n386), 
	.A2(n387), 
	.A1(n388));
   na02s02 U626 (.Z(n661), 
	.A2(n521), 
	.A1(n514));
   in01s02 U627 (.ZN(n545), 
	.I(n541));
   in01f01 U628 (.ZN(n387), 
	.I(n664));
   ao21s01 U629 (.ZN(n367), 
	.B(n368), 
	.A2(n369), 
	.A1(n449));
   na02s02 U630 (.Z(n633), 
	.A2(i_rx_phy_bit_cnt_2_), 
	.A1(n449));
   na02s02 U631 (.Z(n375), 
	.A2(i_rx_phy_bit_cnt_0_), 
	.A1(i_rx_phy_bit_cnt_1_));
   na02s01 U632 (.Z(n513), 
	.A2(i_tx_phy_one_cnt_0_), 
	.A1(i_tx_phy_one_cnt_1_));
   na03s01 U633 (.Z(n624), 
	.A3(i_rx_phy_one_cnt_0_), 
	.A2(i_rx_phy_sd_nrzi), 
	.A1(n491));
   oa21s02 U634 (.ZN(n227), 
	.B(n357), 
	.A2(n302), 
	.A1(n359));
   in01f03 U635 (.ZN(n521), 
	.I(n539));
   in01f03 U636 (.ZN(n427), 
	.I(n539));
   in01f01 U637 (.ZN(n206), 
	.I(n585));
   in01m02 U638 (.ZN(n362), 
	.I(LineState_o[1]));
   na02s03 U639 (.Z(n580), 
	.A2(n448), 
	.A1(n680));
   bf01s01 U640 (.Z(n370), 
	.I(n680));
   oa22s03 U641 (.ZN(n702), 
	.B2(n356), 
	.B1(n547), 
	.A2(n457), 
	.A1(n548));
   na02s03 U642 (.Z(n512), 
	.A2(n462), 
	.A1(n642));
   oa21s06 U643 (.ZN(n193), 
	.B(n373), 
	.A2(n440), 
	.A1(n376));
   oa21s03 U644 (.ZN(n373), 
	.B(n397), 
	.A2(n374), 
	.A1(n633));
   na02s03 U645 (.Z(n398), 
	.A2(n521), 
	.A1(n399));
   na02s03 U646 (.Z(n374), 
	.A2(n375), 
	.A1(n440));
   in01m02 U647 (.ZN(n376), 
	.I(n632));
   in01m02 U648 (.ZN(n538), 
	.I(n530));
   oa21s01 U649 (.ZN(n388), 
	.B(n403), 
	.A2(n663), 
	.A1(i_rx_phy_fs_state_1_));
   bf01m03 U650 (.Z(n390), 
	.I(n680));
   or02s01 U651 (.Z(n395), 
	.A2(n662), 
	.A1(n396));
   na03s03 U652 (.Z(n401), 
	.A3(n402), 
	.A2(n427), 
	.A1(n476));
   na02s03 U653 (.Z(n404), 
	.A2(n447), 
	.A1(n466));
   na02s03 U654 (.Z(n411), 
	.A2(n528), 
	.A1(n642));
   na02s03 U655 (.Z(n412), 
	.A2(n529), 
	.A1(n307));
   na02s03 U656 (.Z(n642), 
	.A2(n413), 
	.A1(n663));
   na02s03 U657 (.Z(n413), 
	.A2(rst), 
	.A1(i_rx_phy_fs_state_0_));
   na02s01 U658 (.Z(n414), 
	.A2(n384), 
	.A1(n662));
   or02s01 U659 (.Z(n515), 
	.A2(n709), 
	.A1(n539));
   na02s03 U660 (.Z(n420), 
	.A2(i_rx_phy_sd_nrzi), 
	.A1(n312));
   in01m03 U661 (.ZN(n653), 
	.I(n421));
   na02s03 U662 (.Z(n421), 
	.A2(DataIn_o[7]), 
	.A1(n312));
   in01m03 U663 (.ZN(n654), 
	.I(n422));
   in01m03 U664 (.ZN(n655), 
	.I(n423));
   na02s03 U665 (.Z(n423), 
	.A2(DataIn_o[5]), 
	.A1(n312));
   na02s03 U666 (.Z(n424), 
	.A2(DataIn_o[4]), 
	.A1(n660));
   in01m03 U667 (.ZN(n658), 
	.I(n426));
   oa21s01 U668 (.ZN(n601), 
	.B(n468), 
	.A2(n358), 
	.A1(i_tx_phy_state_1_));
   oa21s01 U669 (.ZN(n211), 
	.B(rst), 
	.A2(n610), 
	.A1(n611));
   ao22s01 U670 (.ZN(n594), 
	.B2(i_tx_phy_append_eop_sync2), 
	.B1(n417), 
	.A2(i_tx_phy_append_eop_sync1), 
	.A1(n370));
   oa21s01 U671 (.ZN(n197), 
	.B(rst), 
	.A2(n678), 
	.A1(n679));
   ao22s01 U672 (.ZN(n596), 
	.B2(n370), 
	.B1(i_tx_phy_append_eop_sync2), 
	.A2(i_tx_phy_append_eop_sync3), 
	.A1(n595));
   oa21s01 U673 (.ZN(n595), 
	.B(n355), 
	.A2(i_tx_phy_append_eop_sync4), 
	.A1(n356));
   oa21s01 U674 (.ZN(n578), 
	.B(n670), 
	.A2(n577), 
	.A1(n309));
   in01s01 U675 (.ZN(n683), 
	.I(n681));
   oa21s01 U676 (.ZN(n214), 
	.B(n608), 
	.A2(n473), 
	.A1(n534));
   in01s01 U677 (.ZN(n690), 
	.I(n685));
   oa21s01 U678 (.ZN(n562), 
	.B(n448), 
	.A2(i_tx_phy_hold_reg_d[0]), 
	.A1(n537));
   oa21s01 U679 (.ZN(n588), 
	.B(n537), 
	.A2(n586), 
	.A1(n417));
   oa21s01 U680 (.ZN(n224), 
	.B(n668), 
	.A2(n534), 
	.A1(n351));
   in01s01 U681 (.ZN(n693), 
	.I(n691));
   oa21s01 U682 (.ZN(n647), 
	.B(n515), 
	.A2(n428), 
	.A1(n521));
   in01s01 U683 (.ZN(n528), 
	.I(n644));
   oa21s02 U684 (.ZN(n182), 
	.B(n654), 
	.A2(n313), 
	.A1(n483));
   in01f01 U685 (.ZN(n218), 
	.I(n594));
   oa22s01 U686 (.ZN(n219), 
	.B2(n534), 
	.B1(n444), 
	.A2(n355), 
	.A1(n464));
   oa22s01 U687 (.ZN(n212), 
	.B2(n534), 
	.B1(n442), 
	.A2(n355), 
	.A1(n460));
   oa22s01 U688 (.ZN(n213), 
	.B2(n534), 
	.B1(n437), 
	.A2(n355), 
	.A1(n442));
   na02s01 U689 (.Z(n678), 
	.A2(n521), 
	.A1(n677));
   na02s01 U690 (.Z(n679), 
	.A2(n539), 
	.A1(n172));
   oa22s01 U691 (.ZN(n523), 
	.B2(n479), 
	.B1(i_tx_phy_ld_data), 
	.A2(n550), 
	.A1(n441));
   in01f01 U692 (.ZN(n676), 
	.I(n675));
   na02s01 U693 (.Z(n606), 
	.A2(n436), 
	.A1(i_tx_phy_tx_ip));
   na02s01 U694 (.Z(n649), 
	.A2(i_rx_phy_one_cnt_2_), 
	.A1(n372));
   na02s01 U695 (.Z(n625), 
	.A2(n372), 
	.A1(n428));
   na02s01 U696 (.Z(n582), 
	.A2(rst), 
	.A1(i_tx_phy_bit_cnt_0_));
   ao21s01 U697 (.ZN(n634), 
	.B(n417), 
	.A2(n662), 
	.A1(rst));
   na02s01 U698 (.Z(n622), 
	.A2(i_rx_phy_one_cnt_0_), 
	.A1(n428));
   in01f01 U699 (.ZN(n567), 
	.I(n566));
   ao21s01 U700 (.ZN(n568), 
	.B(n439), 
	.A2(n587), 
	.A1(i_tx_phy_hold_reg_d[5]));
   oa22s01 U701 (.ZN(n569), 
	.B2(n561), 
	.B1(n562), 
	.A2(n471), 
	.A1(n565));
   ao21s01 U702 (.ZN(n621), 
	.B(n618), 
	.A2(n619), 
	.A1(n620));
   ao21s01 U703 (.ZN(n620), 
	.B(n534), 
	.A2(n314), 
	.A1(i_rx_phy_sd_r));
   na02s01 U704 (.Z(n586), 
	.A2(rst), 
	.A1(n448));
   na02s01 U705 (.Z(n699), 
	.A2(rst_cnt[3]), 
	.A1(n456));
   ao21s01 U706 (.ZN(n575), 
	.B(n573), 
	.A2(n390), 
	.A1(n574));
   oa22s01 U707 (.ZN(n664), 
	.B2(i_rx_phy_fs_state_1_), 
	.B1(i_rx_phy_fs_state_2_), 
	.A2(i_rx_phy_rxdp_s), 
	.A1(n453));
   na02s01 U708 (.Z(n529), 
	.A2(n490), 
	.A1(i_rx_phy_fs_state_1_));
   na02s01 U709 (.Z(n646), 
	.A2(rst), 
	.A1(i_rx_phy_fs_state_2_));
   na02s01 U710 (.Z(n612), 
	.A2(rst), 
	.A1(i_rx_phy_shift_en));
   na02s01 U711 (.Z(n599), 
	.A2(i_tx_phy_state_1_), 
	.A1(n463));
   or02s01 U712 (.Z(n510), 
	.A2(i_tx_phy_state_0_), 
	.A1(n356));
   oa22s01 U713 (.ZN(n618), 
	.B2(RxActive_o), 
	.B1(n356), 
	.A2(n455), 
	.A1(n355));
   oa22s01 U714 (.ZN(n675), 
	.B2(phy_tx_mode), 
	.B1(n436), 
	.A2(i_tx_phy_sd_nrzi_o), 
	.A1(n674));
   oa22s01 U715 (.ZN(n216), 
	.B2(n534), 
	.B1(n436), 
	.A2(n355), 
	.A1(n475));
   or03s01 U716 (.Z(n602), 
	.A3(n601), 
	.A2(n600), 
	.A1(n599));
   or02s01 U717 (.Z(n638), 
	.A2(i_rx_phy_rxdp_s), 
	.A1(n453));
   or03s01 U718 (.Z(n665), 
	.A3(n663), 
	.A2(n450), 
	.A1(i_rx_phy_fs_state_2_));
endmodule

